### PR TITLE
Fixes bug when adding middleware to route.

### PR DESCRIPTION
**Pull request by xqus**

### CODE REVIEW

**Comment by evilsocket** [comment]
are u sure this is a bug? I've found ppl using auth:api ....

**Comment by xqus** [comment]
Yes, If you inspect response headers before and after you will see the X-RateLimit-Limit and 
X-RateLimit-Remaining from the throllte middleware in the API middleware group.

**Comment by evilsocket** [comment]
See here https://laravel.com/docs/5.2/authentication ( search for "auth:api" )

**Comment by xqus** [comment]
> When attaching the auth middleware to a route, you may also specify which guard should be used to perform the authentication

So that specifies that you should use the api guard for authentication. It's not adding both auth and api middleware, as I assume was the goal.

**Comment by evilsocket** [comment]
no, the goal was to authenticate against /api/v1/ using the api_token GET parameter instead of the normal user session ... before assuming or fixing bugs, please check the laravel documentation.

**Pull request closed without merging**
